name: Build Covid Detector

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      working-directory: ./ML-Example-App  
      run: chmod +x ./gradlew
    - name: Build with Gradle
      working-directory: ./ML-Example-App  
      run: ./gradlew build
  apk:
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      name: Generate APK
      
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace
          working-directory: ./coviddetector
        - name: Upload APK
          uses: actions/upload-artifact@v2.1.2
          with:
            name: app
            path: coviddetector/app/build/outputs/apk/debug/app-debug.apk
